# Generated by Django 4.0.2 on 2022-02-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mamoo', '0002_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
