# Generated by Django 4.0.2 on 2022-02-03 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mamoo', '0003_remove_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mamoo',
            name='profile',
        ),
        migrations.AddField(
            model_name='mamoo',
            name='user',
            field=models.ForeignKey(default='poop', on_delete=django.db.models.deletion.CASCADE, related_name='mamoo', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
