# Generated by Django 4.0.2 on 2022-02-03 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mamoo', '0004_remove_mamoo_profile_mamoo_user_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mamoo',
            name='user',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='mamoo', to=settings.AUTH_USER_MODEL),
        ),
    ]
