# Generated by Django 4.0.2 on 2022-02-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mamoo', '0006_alter_mamoo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mamoo',
            name='user',
        ),
    ]
